# Generated by Django 4.2.1 on 2023-07-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticapp', '0003_alter_team_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
